import { supabase } from './auth/supabase-config.js';

const projectList=document.getElementById('projectList');
const mobileProjectList=document.getElementById('mobileProjectList');
const stats={total:document.getElementById('statTotal'),active:document.getElementById('statActive'),trial:document.getElementById('statTrial'),expired:document.getElementById('statExpired')};

function statusOf(project){const s=String(project.status||'draft').toLowerCase();if(s.includes('expired')||s.includes('inactive'))return'expired';if(s.includes('trial'))return'trial';return'active';}
function safeName(user,profile){return profile?.name||user.user_metadata?.name||user.email?.split('@')[0]||'User';}
function setIdentity(user,profile){const name=safeName(user,profile);document.getElementById('desktopGreeting').textContent=`Welcome back, ${name}! 👋`;document.getElementById('profileName').textContent=name;document.getElementById('profileInitial').textContent=name[0].toUpperCase();document.getElementById('mobileProfileInitial').textContent=name[0].toUpperCase();document.getElementById('mobileGreeting').textContent=`Hello, ${name} 👋`;}
function updateStats(projects){const c={total:projects.length,active:0,trial:0,expired:0};projects.forEach(p=>c[statusOf(p)]++);Object.keys(stats).forEach(k=>stats[k].textContent=String(c[k]));}
function emptyState(){projectList.innerHTML='<div class="empty-project-card"><h3>No apps yet</h3><p>Create your first real app to see it here.</p><a class="card-button" href="create-app-v2.html">Create App →</a></div>';mobileProjectList.innerHTML='<div class="mobile-app-row"><span><strong>No apps yet</strong><small>Create your first app to get started.</small></span></div>';}
function desktopCard(p){const s=statusOf(p),el=document.createElement('article');el.className='app-card';el.innerHTML=`<div class="app-icon">${(p.name||'A')[0].toUpperCase()}</div><h3></h3><p></p><span class="status ${s}-status">${s}</span><div><a>✎ Edit App</a><a>Preview</a></div>`;el.querySelector('h3').textContent=p.name||'Untitled App';el.querySelector('p').textContent=p.description||'No description';const links=el.querySelectorAll('a');links[0].href=`builder-v2.html?projectId=${encodeURIComponent(p.id)}`;links[1].href=`preview.html?projectId=${encodeURIComponent(p.id)}`;return el;}
function mobileCard(p){const s=statusOf(p),el=document.createElement('a');el.className='mobile-app-row';el.href=`builder-v2.html?projectId=${encodeURIComponent(p.id)}`;const updated=p.updated_at?new Date(p.updated_at).toLocaleDateString():'';el.innerHTML=`<span class="mobile-app-icon purple-icon"></span><span><strong></strong><small></small></span><em class="${s}">${s}</em><b>›</b>`;el.querySelector('.mobile-app-icon').textContent=(p.name||'A')[0].toUpperCase();el.querySelector('strong').textContent=p.name||'Untitled App';el.querySelector('small').textContent=updated?`Updated ${updated}`:'Ready to edit';return el;}
function render(projects){projectList.innerHTML='';mobileProjectList.innerHTML='';updateStats(projects);if(!projects.length){emptyState();return;}projects.forEach(p=>{projectList.appendChild(desktopCard(p));mobileProjectList.appendChild(mobileCard(p));});}
async function logout(){await supabase.auth.signOut();window.location.replace('landing/index.html');}
document.getElementById('logoutButton')?.addEventListener('click',logout);document.getElementById('mobileLogoutButton')?.addEventListener('click',logout);

async function init(){const {data:{user},error}=await supabase.auth.getUser();if(error||!user){window.location.replace('auth/sign-in.html');return;}const {data:profile}=await supabase.from('users').select('name,email').eq('id',user.id).maybeSingle();setIdentity(user,profile);projectList.innerHTML='<div class="loading-card">Loading apps...</div>';mobileProjectList.innerHTML='<div class="mobile-app-row"><span><strong>Loading apps...</strong></span></div>';const {data:projects,error:projectError}=await supabase.from('projects').select('id,name,description,start_mode,status,updated_at').eq('user_id',user.id).order('updated_at',{ascending:false});if(projectError)throw projectError;render(projects||[]);}
init().catch(error=>{console.error(error);projectList.innerHTML='<div class="empty-project-card"><h3>Could not load your apps</h3><p>Please refresh and try again.</p></div>';mobileProjectList.innerHTML='<div class="mobile-app-row"><span><strong>Could not load apps</strong><small>Please refresh and try again.</small></span></div>';});