import { supabase } from './auth/supabase-config.js';
import { normalizeDefinition, normalizeComponents } from './app-definition.js';
const canvas=document.getElementById('previewCanvas'),info=document.getElementById('previewInfo'),back=document.getElementById('backButton'),home=document.getElementById('homeButton');const q=new URLSearchParams(location.search),projectId=q.get('projectId');let definition,project,currentPageId=q.get('page')||'home';
const pageId=v=>{if(definition?.pages?.[v])return v;const x=String(v||'').toLowerCase();return Object.entries(definition?.pages||{}).find(([id,p])=>id.toLowerCase()===x||String(p.name||'').toLowerCase()===x)?.[0]||null;};
function go(v){const id=pageId(v);if(!id)return false;currentPageId=id;const u=new URL(location.href);u.searchParams.set('page',id);history.pushState({},'',u);render();return true;}
function btn(label,fn){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=fn;b.style.cssText='padding:9px 13px;border:0;border-radius:9px;background:#5b45f4;color:white;font-weight:700;cursor:pointer';return b;}
function renderComponent(c){const p=c.props||{},w=document.createElement('section');w.className='preview-item';let e;
if(c.type==='Heading'){e=document.createElement('h1');e.textContent=p.text||'Your Heading';Object.assign(e.style,{fontSize:(+p.size||28)+'px',fontWeight:p.weight||700,color:p.color||'#111827',textAlign:p.align||'left'});w.append(e);}
else if(c.type==='Text'){e=document.createElement('p');e.textContent=p.text||'Add your text here.';w.append(e);}
else if(c.type==='Button'){e=btn(p.label||'Get Started',()=>p.link&&go(p.link));w.append(e);}
else if(c.type==='Image'){if(p.url){e=document.createElement('img');e.src=p.url;e.alt=p.alt||'Image';e.style.maxWidth='100%';w.append(e);}else w.textContent='Image URL not set';}
else if(c.type==='Video'||c.type==='YouTube'){e=document.createElement('iframe');e.src=p.url||'';e.title=p.title||c.type;e.allow='autoplay; encrypted-media; picture-in-picture';e.style.cssText='width:100%;min-height:230px;border:0;border-radius:12px';w.append(e);}
else if(c.type==='Input'){e=document.createElement('input');e.placeholder=p.placeholder||p.label||'';e.type=p.inputType||'text';e.required=!!p.required;e.style.cssText='width:100%;padding:11px;border:1px solid #d6d9e4;border-radius:9px';w.append(e);}
else if(c.type==='Card'){e=document.createElement('div');e.innerHTML=`<h3>${p.title||'Card Title'}</h3><p>${p.text||'Card content'}</p>`;e.style.cssText='padding:18px;border:1px solid #e5e7ef;border-radius:14px';w.append(e);}
else if(c.type==='Container'){e=document.createElement('div');e.textContent='Container';e.style.cssText=`padding:${+p.padding||16}px;background:${p.background||'#fff'};border:1px solid #ebe8ff;border-radius:${+p.radius||12}px`;w.append(e);}
else if(c.type==='Icon'){e=document.createElement('span');e.textContent=p.name||'★';e.style.fontSize=(+p.size||28)+'px';w.append(e);}
else if(c.type==='List'){e=document.createElement('ul');(p.items||[]).forEach(x=>{const li=document.createElement('li');li.textContent=x;e.append(li)});w.append(e);}
else if(['Menu','Navbar','Social Links'].includes(c.type)){e=document.createElement('nav');e.style.cssText='display:flex;gap:18px;flex-wrap:wrap;align-items:center';if(c.type==='Navbar'){const b=document.createElement('strong');b.textContent=p.brand||'My App';e.append(b)};(p.items||p.links||[]).forEach(x=>{const a=btn(x,()=>go(x));e.append(a)});w.append(e);}
else if(c.type==='Divider'){e=document.createElement('hr');w.append(e);}
else if(c.type==='Spacer'){e=document.createElement('div');e.style.height=(+p.height||24)+'px';w.append(e);}
else if(c.type==='Footer'){e=document.createElement('footer');e.textContent=p.text||'© 2026 My App';e.style.padding='20px';w.append(e);}
else if(c.type==='Form'||c.type==='Login'||c.type==='Signup'){e=document.createElement('form');const h=document.createElement('h2');h.textContent=p.title||'Form';e.append(h);['Email','Password'].forEach(x=>{const i=document.createElement('input');i.placeholder=x;i.type=x==='Password'?'password':'email';i.style.cssText='display:block;width:100%;padding:10px;margin:8px 0';e.append(i)});e.append(btn(p.button||p.submit||'Submit',()=>{}));w.append(e);}
else if(c.type==='Checkbox'||c.type==='Radio'){e=document.createElement('label');const i=document.createElement('input');i.type=c.type==='Checkbox'?'checkbox':'radio';e.append(i,document.createTextNode(' '+(p.label||'Option')));w.append(e);}
else if(c.type==='Select'){e=document.createElement('select');(p.options||[]).forEach(x=>{const o=document.createElement('option');o.textContent=x;e.append(o)});w.append(e);}
else if(c.type==='Tabs'){e=document.createElement('div');const nav=document.createElement('div');(p.tabs||[]).forEach((x,i)=>nav.append(btn(x,()=>{body.textContent=x+' content'})));const body=document.createElement('div');body.textContent=(p.tabs||['Overview'])[p.active||0]+' content';body.style.padding='16px';e.append(nav,body);w.append(e);}
else if(c.type==='Accordion'){e=document.createElement('div');(p.items||[]).forEach(x=>{const d=document.createElement('details'),s=document.createElement('summary');s.textContent=x[0];const a=document.createElement('p');a.textContent=x[1];d.append(s,a);e.append(d)});w.append(e);}
else if(c.type==='Modal'){w.append(btn(p.button||'Open Modal',()=>alert((p.title||'Modal')+'\n'+(p.text||''))));}
else if(c.type==='Table'){e=document.createElement('table');e.border='1';const h=document.createElement('tr');(p.headers||[]).forEach(x=>{const th=document.createElement('th');th.textContent=x;h.append(th)});e.append(h);(p.rows||[]).forEach(r=>{const tr=document.createElement('tr');r.forEach(x=>{const td=document.createElement('td');td.textContent=x;tr.append(td)});e.append(tr)});w.append(e);}
else if(c.type==='Search'){e=document.createElement('input');e.placeholder=p.placeholder||'Search...';w.append(e);}
else if(c.type==='Avatar'){e=document.createElement(p.url?'img':'div');if(p.url)e.src=p.url;else e.textContent=(p.name||'U')[0];e.style.cssText='width:48px;height:48px;border-radius:50%;display:grid;place-items:center;background:#eee;object-fit:cover';w.append(e);}
else if(c.type==='Badge'){e=document.createElement('span');e.textContent=p.text||'New';e.style.cssText='padding:5px 9px;border-radius:999px;background:#5b45f4;color:white';w.append(e);}
else if(c.type==='Progress'){e=document.createElement('progress');e.value=p.value||0;e.max=p.max||100;e.style.width='100%';w.append(e);}
else if(c.type==='Slider'){e=document.createElement('input');e.type='range';e.min=p.min||0;e.max=p.max||100;e.value=p.value||50;w.append(e);}
else if(c.type==='Date Picker'){e=document.createElement('input');e.type='date';w.append(e);}
else if(c.type==='Map'){e=document.createElement('div');e.textContent='📍 '+(p.address||'Map location');e.style.cssText='min-height:160px;display:grid;place-items:center;background:#e8edf5;border-radius:12px';w.append(e);}
else if(c.type==='Audio Player'){e=document.createElement('audio');e.controls=true;e.src=p.url||'';w.append(e);}
else if(c.type==='Gallery'){e=document.createElement('div');e.style.cssText='display:grid;grid-template-columns:repeat(3,1fr);gap:6px';(p.images||[]).forEach(x=>{const im=document.createElement('img');im.src=x;im.style.width='100%';e.append(im)});w.append(e);}
else if(c.type==='Carousel'){e=document.createElement('div');let i=p.active||0;const label=document.createElement('strong');label.textContent=(p.items||['Slide 1'])[i];e.append(btn('‹',()=>{i=(i-1+(p.items||[]).length)%(p.items||[]).length;label.textContent=p.items[i]}),label,btn('›',()=>{i=(i+1)%(p.items||[]).length;label.textContent=p.items[i]}));w.append(e);}
else if(c.type==='Pricing'){e=document.createElement('div');e.innerHTML=`<h2>${p.title||'Pro'}</h2><h1>${p.price||'₹999'} <small>${p.period||'/month'}</small></h1>`;w.append(e);}
else if(c.type==='Testimonials'){e=document.createElement('blockquote');e.textContent='“'+(p.quote||'Great product!')+'” — '+(p.author||'Customer');w.append(e);}
return w;}
function render(){const page=definition?.pages?.[currentPageId];if(!page){canvas.textContent='Page not found';return}info.textContent=`${project.name||'Untitled App'} • ${page.name}`;canvas.innerHTML='';canvas.style.background=page.styles?.background||'#fff';canvas.style.padding=page.styles?.padding||'24px';normalizeComponents(page.components||[]).forEach(c=>{const x=renderComponent(c);if(x.children.length||x.textContent)canvas.append(x)});}
async function load(){if(!projectId)throw Error('Missing project');const a=await supabase.auth.getUser();if(a.error)throw a.error;if(!a.data.user){location.replace('auth/sign-in.html');return}const r=await supabase.from('projects').select('id,user_id,name,description,app_definition,pages').eq('id',projectId).eq('user_id',a.data.user.id).maybeSingle();if(r.error)throw r.error;if(!r.data)throw Error('Project not found');project=r.data;definition=normalizeDefinition(project);currentPageId=pageId(currentPageId)||Object.keys(definition.pages)[0]||'home';render();}
back.onclick=()=>location.href=`builder-v2.html?projectId=${encodeURIComponent(projectId||'')}`;home.onclick=()=>location.href='dashboard/index.html';addEventListener('popstate',render);load().catch(e=>{info.textContent='Preview failed';canvas.textContent=e.message||'Could not load preview';});