import { supabase } from './auth/supabase-config.js';
import { normalizeDefinition, normalizeComponents } from './app-definition.js';

const canvas=document.getElementById('previewCanvas'),info=document.getElementById('previewInfo'),back=document.getElementById('backButton'),home=document.getElementById('homeButton');
const q=new URLSearchParams(location.search),projectId=q.get('projectId');
let definition,project,currentPageId=q.get('page')||'home';

const pageId=v=>{if(definition?.pages?.[v])return v;const x=String(v||'').toLowerCase();return Object.entries(definition?.pages||{}).find(([id,p])=>id.toLowerCase()===x||String(p.name||'').toLowerCase()===x||String(p.slug||'').toLowerCase()===x)?.[0]||null;};
function go(v){const id=pageId(v);if(!id)return false;currentPageId=id;const u=new URL(location.href);u.searchParams.set('page',id);history.pushState({},'',u);render();return true;}
function btn(label,fn){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=fn;b.style.cssText='padding:9px 13px;border:0;border-radius:9px;background:#5b45f4;color:white;font-weight:700;cursor:pointer';return b;}
function renderHeader(c){const p=c.props||{},root=document.createElement('header');root.style.cssText=`position:relative;display:flex;align-items:center;justify-content:space-between;min-height:64px;padding:0 16px;background:${p.menuBackground||'#fff'};color:${p.titleColor||'#111827'};border-radius:12px 12px 0 0;border-bottom:1px solid rgba(0,0,0,.08)`;const title=document.createElement('strong');title.textContent=p.title||project?.name||'My App';title.style.cssText=`font-family:${p.fontFamily||'Inter'};font-size:${+p.fontSize||20}px;font-weight:${p.fontWeight||'800'};color:${p.titleColor||'#111827'}`;const toggle=document.createElement('button');toggle.type='button';toggle.textContent=p.menuIcon||'☰';toggle.style.cssText=`width:38px;height:38px;border:1px solid rgba(0,0,0,.12);border-radius:9px;background:rgba(0,0,0,.03);color:${p.menuIconColor||'#111827'};font-size:${+p.menuIconSize||22}px;cursor:pointer`;const menu=document.createElement('div');menu.style.cssText=`display:none;position:absolute;top:70px;${p.menuSide==='left'?'left:10px':'right:10px'};z-index:20;width:220px;padding:8px;border-radius:12px;background:${p.menuPanelBackground||'#0f172a'};box-shadow:0 18px 45px rgba(0,0,0,.35)`;(p.items||Object.keys(definition.pages)).forEach(id=>{const page=definition.pages[id];if(!page)return;const item=document.createElement('button');item.type='button';item.textContent=page.name;item.style.cssText=`display:block;width:100%;padding:10px 11px;border:0;border-radius:8px;background:transparent;color:${p.menuPanelColor||'#fff'};text-align:left;font-weight:700;cursor:pointer`;item.onclick=()=>{menu.style.display='none';go(id)};menu.appendChild(item)});toggle.onclick=()=>{menu.style.display=menu.style.display==='none'?'block':'none'};if(p.brandSide==='center'||p.menuSide==='left')root.append(toggle,title);else root.append(title,toggle);root.append(menu);return root;}
function renderComponent(c){const p=c.props||{},w=document.createElement('section');w.className='preview-item';let e;
if(c.type==='Header')w.append(renderHeader(c));
else if(c.type==='Navigation'){e=document.createElement('nav');e.style.cssText='display:flex;gap:14px;flex-wrap:wrap';(p.items||[]).forEach(x=>{const b=btn(x,()=>go(x));e.append(b)});w.append(e)}
else if(c.type==='Hero Section'){e=document.createElement('div');e.style.cssText='padding:36px 20px;border-radius:14px;background:#111827;color:#fff';const h=document.createElement('h2');h.textContent=p.title;const t=document.createElement('p');t.textContent=p.text;e.append(h,t,btn(p.button||'Get Started',()=>{}));w.append(e)}
else if(c.type==='Buttons'){e=btn(p.label||'Get Started',()=>p.link&&go(p.link));w.append(e)}
else if(c.type==='Cards'){e=document.createElement('div');e.style.cssText='padding:18px;border:1px solid #e5e7eb;border-radius:14px';const h=document.createElement('h3');h.textContent=p.title||'Card title';const t=document.createElement('p');t.textContent=p.text||'Card content';e.append(h,t);w.append(e)}
else if(c.type==='Images'){if(p.url){e=document.createElement('img');e.src=p.url;e.alt=p.alt||'Image';e.style.maxWidth='100%';w.append(e)}else w.textContent='Image URL not set'}
else if(c.type==='Videos'){e=document.createElement('video');e.controls=p.controls!==false;e.autoplay=!!p.autoplay;e.src=p.url||'';e.style.width='100%';w.append(e)}
else if(c.type==='Music Player'){const h=document.createElement('strong');h.textContent=p.title||'Now Playing';e=document.createElement('audio');e.controls=true;e.src=p.src||'';w.append(h,e)}
else if(c.type==='Forms'){e=document.createElement('form');e.onsubmit=x=>x.preventDefault();const h=document.createElement('h3');h.textContent=p.title||'Contact us';e.append(h);(p.fields||[]).forEach(x=>{const i=document.createElement('input');i.placeholder=x;i.style.cssText='display:block;width:100%;margin:7px 0;padding:10px;border:1px solid #d1d5db;border-radius:8px';e.append(i)});e.append(btn('Submit',()=>{}));w.append(e)}
else if(c.type==='Footer / Bottom'){e=document.createElement('nav');e.style.cssText='display:flex;justify-content:space-around;padding:14px;border-top:1px solid #e5e7eb';(p.items||[]).forEach(x=>e.append(btn(x,()=>go(x))));w.append(e)}
else if(c.type==='Footer'){e=document.createElement('footer');e.textContent=p.text||'© 2026 My App';e.style.padding='20px';w.append(e)}
else if(c.type==='Input'){e=document.createElement('input');e.placeholder=p.placeholder||p.label||'';e.type=p.inputType||'text';e.required=!!p.required;e.style.cssText='width:100%;padding:11px;border:1px solid #d6d9e4;border-radius:9px';w.append(e)}
else if(c.type==='Text'){e=document.createElement('p');e.textContent=p.text||'';w.append(e)}
else if(c.type==='Heading'){e=document.createElement('h1');e.textContent=p.text||'';w.append(e)}
else if(c.type==='Image'){if(p.url){e=document.createElement('img');e.src=p.url;e.style.maxWidth='100%';w.append(e)}}
else if(c.type==='Container'){e=document.createElement('div');e.textContent='Container';e.style.cssText=`padding:${+p.padding||16}px;background:${p.background||'#fff'};border-radius:${+p.radius||12}px`;w.append(e)}
else if(c.type==='Icon'){e=document.createElement('span');e.textContent=p.name||'★';e.style.fontSize=(+p.size||28)+'px';w.append(e)}
else if(c.type==='List'){e=document.createElement('ul');(p.items||[]).forEach(x=>{const li=document.createElement('li');li.textContent=x;e.append(li)});w.append(e)}
else if(c.type==='Divider'){e=document.createElement('hr');w.append(e)}
else if(c.type==='Spacer'){e=document.createElement('div');e.style.height=(+p.height||24)+'px';w.append(e)}
else {e=document.createElement('div');e.textContent=p.text||c.type;w.append(e)}
return w;}
function render(){const page=definition?.pages?.[currentPageId];if(!page){canvas.textContent='Page not found';return}info.textContent=`${project.name||'Untitled App'} • ${page.name}`;canvas.innerHTML='';canvas.style.background=page.styles?.background||'#fff';canvas.style.padding=page.styles?.padding||'24px';normalizeComponents(page.components||[]).forEach(c=>{const x=renderComponent(c);if(x.children.length||x.textContent)canvas.append(x)});}
async function load(){if(!projectId)throw Error('Missing project');const a=await supabase.auth.getUser();if(a.error)throw a.error;if(!a.data.user){location.replace('auth/sign-in.html');return}const r=await supabase.from('projects').select('id,user_id,name,description,app_definition,pages').eq('id',projectId).eq('user_id',a.data.user.id).maybeSingle();if(r.error)throw r.error;if(!r.data)throw Error('Project not found');project=r.data;definition=normalizeDefinition(project);currentPageId=pageId(currentPageId)||Object.keys(definition.pages)[0]||'home';render();}
back.onclick=()=>location.href=`builder-v2.html?projectId=${encodeURIComponent(projectId||'')}`;home.onclick=()=>location.href='dashboard/index.html';addEventListener('popstate',render);load().catch(e=>{info.textContent='Preview failed';canvas.textContent=e.message||'Could not load preview';});
