import { supabase } from './auth/supabase-config.js';
import { renderApiActionPanel } from './api-action-panel.js';
const params=new URLSearchParams(location.search),projectId=params.get('projectId');
const state={project:null,workflows:[]},$=id=>document.getElementById(id);
const TRIGGERS=[{id:'click',label:'Button Clicked'},{id:'submit',label:'Form Submitted'},{id:'page-load',label:'Page Loaded'}],ACTIONS=[{id:'navigate',label:'Navigate to Page'},{id:'show-message',label:'Show Message'},{id:'set-value',label:'Set Value'},{id:'show-hide',label:'Show / Hide Component'},{id:'api-call',label:'API Request'}];
const uid=(p='workflow')=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const defaultWorkflow=()=>({id:uid(),name:'New Workflow',enabled:true,trigger:{type:'click',componentId:''},actions:[{id:uid('action'),type:'navigate',pageId:'home'}]});
async function save(){if(!state.project)return;const next={...(state.project.app_definition||{}),workflows:state.workflows};const {error}=await supabase.from('projects').update({app_definition:next}).eq('id',state.project.id);if(error){$('message').textContent='Save failed: '+error.message;return false}$('message').textContent='Saved';return true;}
function render(){const list=$('workflowList');if(!list)return;list.innerHTML='';state.workflows.forEach((w,i)=>{const card=document.createElement('article');card.className='workflow-card';card.innerHTML=`<div class="workflow-head"><input class="workflow-name" value="${String(w.name).replace(/"/g,'&quot;')}"><label><input type="checkbox" class="workflow-enabled" ${w.enabled?'checked':''}> Enabled</label></div><div class="workflow-row"><strong>WHEN</strong><select class="trigger-select">${TRIGGERS.map(t=>`<option value="${t.id}" ${w.trigger.type===t.id?'selected':''}>${t.label}</option>`).join('')}</select></div><div class="workflow-row"><strong>DO</strong><select class="action-select">${ACTIONS.map(a=>`<option value="${a.id}" ${w.actions[0]?.type===a.id?'selected':''}>${a.label}</option>`).join('')}</select></div><div class="api-config"></div><div class="workflow-actions"><button class="secondary save-workflow" type="button">Save</button><button class="danger delete-workflow" type="button">Delete</button></div>`;
const action=w.actions[0]||{};const apiBox=card.querySelector('.api-config');const actionSelect=card.querySelector('.action-select');
const drawApi=()=>{apiBox.replaceChildren();if(actionSelect.value==='api-call')renderApiActionPanel(apiBox,action,next=>{w.actions[0]=next});};
card.querySelector('.workflow-name').oninput=e=>{w.name=e.target.value||'Untitled Workflow'};card.querySelector('.workflow-enabled').onchange=e=>{w.enabled=e.target.checked};card.querySelector('.trigger-select').onchange=e=>{w.trigger.type=e.target.value};actionSelect.onchange=e=>{w.actions[0]=e.target.value==='api-call'?{id:uid('action'),type:'api-call',config:{method:'GET',url:'',headers:{},body:null}}:{...action,id:action.id||uid('action'),type:e.target.value};drawApi()};card.querySelector('.save-workflow').onclick=()=>save();card.querySelector('.delete-workflow').onclick=async()=>{state.workflows.splice(i,1);render();await save()};drawApi();list.appendChild(card)})}
async function init(){if(!projectId){$('message').textContent='Open Workflow Builder from an app project.';return}const u=await supabase.auth.getUser();if(u.error||!u.data.user){location.assign(new URL('auth/sign-in.html',location.href));return}const r=await supabase.from('projects').select('id,name,app_definition').eq('id',projectId).eq('user_id',u.data.user.id).maybeSingle();if(r.error||!r.data){$('message').textContent='Project not found.';return}state.project=r.data;state.workflows=Array.isArray(r.data.app_definition?.workflows)?r.data.app_definition.workflows:[];if(!state.workflows.length)state.workflows=[defaultWorkflow()];$('projectName').textContent=r.data.name;render()}
$('addWorkflow')?.addEventListener('click',async()=>{state.workflows.push(defaultWorkflow());render();await save()});$('backBuilder')?.addEventListener('click',()=>location.assign(`builder-v2.html?projectId=${encodeURIComponent(projectId)}`));init();