import { supabase } from '../auth/supabase-config.js';

const projectList=document.getElementById('projectList');
const mobileProjectList=document.getElementById('mobileProjectList');
const stats={total:document.getElementById('statTotal'),active:document.getElementById('statActive'),trial:document.getElementById('statTrial'),expired:document.getElementById('statExpired')};
const logoutButtons=[document.getElementById('logoutButton'),document.getElementById('mobileLogoutButton')].filter(Boolean);
const searchButton=document.getElementById('searchButton');
const searchRow=document.getElementById('searchRow');
const searchInput=document.getElementById('searchInput');
const notificationsButton=document.getElementById('notificationsButton');
const profileButton=document.getElementById('profileButton');
const mobileProfileButton=document.getElementById('mobileProfileButton');
const clearFilterButton=document.getElementById('clearFilterButton');
const statsButtons=[...document.querySelectorAll('.stat[data-filter]')];

let allProjects=[];
let activeFilter='all';
let searchTerm='';
let currentUser=null;
let currentProfile=null;

function statusOf(project){const s=String(project.status||'draft').toLowerCase();if(s.includes('expired')||s.includes('inactive'))return'expired';if(s.includes('trial'))return'trial';return'active';}
function safeName(user,profile){return profile?.name||user.user_metadata?.name||user.email?.split('@')[0]||'User';}
function setIdentity(user,profile){const name=safeName(user,profile);document.getElementById('desktopGreeting').textContent=`Welcome back, ${name}! 👋`;document.getElementById('profileName').textContent=name;document.getElementById('profileInitial').textContent=name[0].toUpperCase();document.getElementById('mobileProfileInitial').textContent=name[0].toUpperCase();document.getElementById('mobileGreeting').textContent=`Hello, ${name} 👋`;}
function updateStats(projects){const c={total:projects.length,active:0,trial:0,expired:0};projects.forEach(p=>c[statusOf(p)]++);Object.keys(stats).forEach(k=>stats[k].textContent=String(c[k]));}
function showEmpty(target,title='No apps found',message='Try a different search or create a new app.'){target.innerHTML=`<div class="empty-project-card"><h3>${title}</h3><p>${message}</p><a class="card-button" href="create-app-v2.html">Create App →</a></div>`;}
function confirmDelete(name){return new Promise(resolve=>{const backdrop=document.createElement('div');backdrop.style.cssText='position:fixed;inset:0;z-index:9999;display:grid;place-items:center;padding:20px;background:rgba(2,5,12,.78);backdrop-filter:blur(8px)';const modal=document.createElement('div');modal.style.cssText='width:min(430px,100%);padding:24px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:#111827;color:#fff;box-shadow:0 28px 90px rgba(0,0,0,.55)';modal.innerHTML='<p style="margin:0 0 6px;color:#a78bfa;font-size:10px;font-weight:900;letter-spacing:.12em">DELETE APP</p><h2 style="margin:0 0 10px;font-size:20px">Delete this app?</h2><p id="deleteCopy" style="margin:0;color:#aeb8c8;line-height:1.5;font-size:12px"></p><div style="display:flex;justify-content:flex-end;gap:8px;margin-top:20px"><button data-cancel type="button" style="min-height:38px;padding:0 14px;border-radius:9px;border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.04);color:#c8d0dd;font-weight:800">Cancel</button><button data-delete type="button" style="min-height:38px;padding:0 14px;border-radius:9px;border:0;background:#dc2626;color:#fff;font-weight:900">Delete App</button></div>';modal.querySelector('#deleteCopy').textContent=`“${name||'Untitled App'}” and all of its saved pages, components and app settings will be permanently removed from your workspace.`;const done=value=>{backdrop.remove();resolve(value)};modal.querySelector('[data-cancel]').onclick=()=>done(false);modal.querySelector('[data-delete]').onclick=()=>done(true);backdrop.onclick=e=>{if(e.target===backdrop)done(false)};const onKey=e=>{if(e.key==='Escape'){document.removeEventListener('keydown',onKey);done(false)}};document.addEventListener('keydown',onKey);backdrop.appendChild(modal);document.body.appendChild(backdrop)});}
async function deleteProject(project){const ok=await confirmDelete(project.name);if(!ok)return;const cards=document.querySelectorAll(`[data-project-id="${CSS.escape(String(project.id))}"]`);cards.forEach(card=>{card.style.opacity='.45';card.style.pointerEvents='none'});try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Not signed in');const {error}=await supabase.from('projects').delete().eq('id',project.id).eq('user_id',user.id);if(error)throw error;try{localStorage.removeItem(`indo:home-layout:${project.id}`)}catch{}await refreshProjects()}catch(error){console.error(error);cards.forEach(card=>{card.style.opacity='';card.style.pointerEvents='' });window.alert(`Could not delete “${project.name||'Untitled App'}”. ${error.message||'Please try again.'}`)}}
function desktopCard(p){const s=statusOf(p),el=document.createElement('article');el.className='app-card';el.dataset.projectId=p.id;el.innerHTML=`<div class="app-icon">${(p.name||'A')[0].toUpperCase()}</div><h3></h3><p></p><span class="status ${s}-status">${s}</span><div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap"><a data-edit>✎ Edit App</a><a data-preview>Preview</a><a data-build-apk>Build APK</a><button data-delete type="button" title="Delete app" style="border:1px solid rgba(220,38,38,.28);background:rgba(220,38,38,.08);color:#fca5a5;border-radius:8px;padding:6px 9px;font-size:11px;font-weight:800;cursor:pointer">Delete</button></div>`;el.querySelector('h3').textContent=p.name||'Untitled App';el.querySelector('p').textContent=p.description||'No description';el.querySelector('[data-edit]').href=`builder-v2.html?projectId=${encodeURIComponent(p.id)}`;el.querySelector('[data-preview]').href=`preview.html?projectId=${encodeURIComponent(p.id)}`;el.querySelector('[data-build-apk]').href=`builder-v2.html?projectId=${encodeURIComponent(p.id)}&action=build-apk`;el.querySelector('[data-delete]').addEventListener('click',()=>deleteProject(p));return el;}
function mobileCard(p){const s=statusOf(p),el=document.createElement('div');el.className='mobile-app-row';el.dataset.projectId=p.id;const updated=p.updated_at?new Date(p.updated_at).toLocaleDateString():'';el.innerHTML=`<div style="display:flex;align-items:center;gap:10px;min-width:0;width:100%"><a data-open href="builder-v2.html?projectId=${encodeURIComponent(p.id)}" style="display:flex;align-items:center;gap:10px;min-width:0;flex:1;color:inherit;text-decoration:none"><span class="mobile-app-icon purple-icon"></span><span style="min-width:0;flex:1"><strong></strong><small></small></span><em class="${s}">${s}</em><b>›</b></a></div><div data-mobile-actions style="display:flex;gap:8px;width:100%;margin-top:10px"><a data-build-apk href="builder-v2.html?projectId=${encodeURIComponent(p.id)}&action=build-apk" style="display:flex;align-items:center;justify-content:center;min-height:38px;flex:1;border:1px solid rgba(139,92,246,.34);background:rgba(124,58,237,.14);color:#dfd5ff;border-radius:9px;padding:0 10px;font-size:11px;font-weight:900;text-decoration:none">Build APK</a><button data-delete type="button" aria-label="Delete app" style="display:flex;align-items:center;justify-content:center;min-height:38px;flex:1;border:1px solid rgba(220,38,38,.25);background:rgba(220,38,38,.08);color:#fca5a5;border-radius:8px;padding:0 10px;font-size:11px;font-weight:800">Delete</button></div>`;el.querySelector('.mobile-app-icon').textContent=(p.name||'A')[0].toUpperCase();el.querySelector('strong').textContent=p.name||'Untitled App';el.querySelector('small').textContent=updated?`Updated ${updated}`:'Ready to edit';el.querySelector('[data-delete]').addEventListener('click',()=>deleteProject(p));return el;}
function filteredProjects(){const q=searchTerm.trim().toLowerCase();return allProjects.filter(p=>{const matchesFilter=activeFilter==='all'||statusOf(p)===activeFilter;const text=`${p.name||''} ${p.description||''}`.toLowerCase();return matchesFilter&&(!q||text.includes(q))})}
function updateFilterUi(){clearFilterButton.style.display=activeFilter==='all'&&!searchTerm?'none':'inline-flex';statsButtons.forEach(btn=>{const active=btn.dataset.filter===activeFilter;btn.style.outline=active?'2px solid rgba(139,92,246,.55)':'none';btn.style.outlineOffset=active?'2px':'0'})}
function render(){const projects=filteredProjects();projectList.innerHTML='';mobileProjectList.innerHTML='';updateStats(allProjects);updateFilterUi();if(!projects.length){showEmpty(projectList,searchTerm?'No matching apps':'No apps in this filter',searchTerm?'Try another name or description.':'Create your first app to get started.');mobileProjectList.innerHTML='<div class="mobile-app-row"><span><strong>No matching apps</strong><small>Try another filter or create a new app.</small></span></div>';return}projects.forEach(p=>{projectList.appendChild(desktopCard(p));mobileProjectList.appendChild(mobileCard(p))})}
async function loadProjects(){const {data:{user},error}=await supabase.auth.getUser();if(error||!user)throw error||new Error('Not signed in');currentUser=user;const {data:projects,error:projectError}=await supabase.from('projects').select('id,name,description,start_mode,status,updated_at').eq('user_id',user.id).order('updated_at',{ascending:false});if(projectError)throw projectError;return projects||[]}
async function refreshProjects(){allProjects=await loadProjects();render()}
function openSearch(){searchRow.style.display='block';searchInput.focus();document.getElementById('projects').scrollIntoView({behavior:'smooth',block:'start'})}
function openProfile(){const existing=document.getElementById('dashboardProfileModal');if(existing){existing.remove();return}const backdrop=document.createElement('div');backdrop.id='dashboardProfileModal';backdrop.style.cssText='position:fixed;inset:0;z-index:9998;display:grid;place-items:center;padding:20px;background:rgba(2,5,12,.7);backdrop-filter:blur(8px)';const name=safeName(currentUser,currentProfile);const email=currentUser?.email||currentProfile?.email||'Not available';const modal=document.createElement('div');modal.style.cssText='width:min(420px,100%);padding:24px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:#111827;color:#fff;box-shadow:0 28px 90px rgba(0,0,0,.55)';modal.innerHTML=`<div style="display:flex;align-items:center;gap:12px"><div style="width:48px;height:48px;display:grid;place-items:center;border-radius:14px;background:linear-gradient(135deg,#7c3aed,#a855f7);font-weight:900;font-size:20px">${name[0].toUpperCase()}</div><div><h2 style="margin:0;font-size:18px">${name}</h2><p style="margin:3px 0 0;color:#9ca8ba;font-size:11px">${email}</p></div></div><div style="display:grid;gap:8px;margin-top:20px"><button data-profile-edit type="button" style="min-height:40px;border:1px solid rgba(255,255,255,.08);border-radius:10px;background:rgba(255,255,255,.04);color:#e7ebf4;font-weight:800">Account settings</button><button data-profile-close type="button" style="min-height:40px;border:0;border-radius:10px;background:#7c3aed;color:#fff;font-weight:900">Close</button></div>`;modal.querySelector('[data-profile-edit]').onclick=()=>window.alert('Profile settings page will be connected here next.');modal.querySelector('[data-profile-close]').onclick=()=>backdrop.remove();backdrop.onclick=e=>{if(e.target===backdrop)backdrop.remove()};backdrop.appendChild(modal);document.body.appendChild(backdrop)}
function openNotifications(){const existing=document.getElementById('dashboardNotifications');if(existing){existing.remove();return}const panel=document.createElement('div');panel.id='dashboardNotifications';panel.style.cssText='position:fixed;right:24px;top:76px;z-index:9997;width:min(360px,calc(100vw - 32px));padding:16px;border:1px solid rgba(255,255,255,.1);border-radius:16px;background:#111827;color:#fff;box-shadow:0 24px 70px rgba(0,0,0,.5)';panel.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><strong>Notifications</strong><button type="button" data-close style="border:0;background:transparent;color:#9ca8ba;font-size:18px">×</button></div><div style="display:grid;gap:8px;margin-top:12px"><div style="padding:11px;border-radius:10px;background:rgba(124,58,237,.08);color:#dbe1ec;font-size:12px">Your dashboard is ready.</div><div style="padding:11px;border-radius:10px;background:rgba(255,255,255,.035);color:#9ca8ba;font-size:12px">Create an app to start building.</div></div>';panel.querySelector('[data-close]').onclick=()=>panel.remove();document.body.appendChild(panel)}
async function logout(){logoutButtons.forEach(button=>{button.disabled=true;button.dataset.originalText=button.textContent;button.textContent='Signing Out...'});try{const {error}=await supabase.auth.signOut();if(error)throw error;window.location.replace('../landing/index.html')}catch(error){console.error(error);logoutButtons.forEach(button=>{button.disabled=false;button.textContent=button.dataset.originalText||'Sign Out'});window.alert('Could not sign out. Please try again.')}}
logoutButtons.forEach(button=>button.addEventListener('click',event=>{event.preventDefault();logout()}));
searchButton?.addEventListener('click',()=>{searchRow.style.display=searchRow.style.display==='none'?'block':'none';if(searchRow.style.display==='block')openSearch()});
searchInput?.addEventListener('input',e=>{searchTerm=e.target.value;render()});
clearFilterButton?.addEventListener('click',()=>{activeFilter='all';searchTerm='';searchInput.value='';render()});
notificationsButton?.addEventListener('click',openNotifications);
profileButton?.addEventListener('click',openProfile);
mobileProfileButton?.addEventListener('click',openProfile);
statsButtons.forEach(btn=>btn.addEventListener('click',()=>{activeFilter=btn.dataset.filter||'all';document.getElementById('projects').scrollIntoView({behavior:'smooth',block:'start'});render()}));
document.querySelectorAll('.nav a[href="#projects"],.mobile-bottom-nav a[href="#projects"]').forEach(link=>link.addEventListener('click',()=>{activeFilter='all';searchTerm='';if(searchInput)searchInput.value='';setTimeout(render,0)}));

async function init(){const {data:{user},error}=await supabase.auth.getUser();if(error||!user){window.location.replace('../auth/sign-in.html');return}const {data:profile}=await supabase.from('users').select('name,email').eq('id',user.id).maybeSingle();currentProfile=profile;setIdentity(user,profile);projectList.innerHTML='<div class="loading-card">Loading apps...</div>';mobileProjectList.innerHTML='<div class="mobile-app-row"><span><strong>Loading apps...</strong></span></div>';allProjects=await loadProjects();render()}
init().catch(error=>{console.error(error);projectList.innerHTML='<div class="empty-project-card"><h3>Could not load your apps</h3><p>Please refresh and try again.</p></div>';mobileProjectList.innerHTML='<div class="mobile-app-row"><span><strong>Could not load apps</strong><small>Please refresh and try again.</small></span></div>'});
