import { normalizeDefinition, normalizeComponents } from './app-definition.js';

const status = document.getElementById('status');
const canvas = document.getElementById('canvas');
const slug = decodeURIComponent(new URLSearchParams(location.search).get('slug') || location.pathname.split('/').filter(Boolean).pop() || '');
const GATE_URL = 'https://lpcfgrphadnppqxpwxjv.supabase.co/functions/v1/live-app-gate';
const btn = (label, fn) => { const b = document.createElement('button'); b.type = 'button'; b.textContent = label; b.onclick = fn; b.style.cssText = 'padding:9px 13px;border:0;border-radius:9px;background:#5b45f4;color:#fff;font-weight:700;cursor:pointer'; return b; };
let definition, project, currentPage = 'home';
function pageId(value){if(definition?.pages?.[value])return value;const x=String(value||'').toLowerCase();return Object.entries(definition?.pages||{}).find(([id,p])=>id.toLowerCase()===x||String(p.name||'').toLowerCase()===x||String(p.slug||'').toLowerCase()===x)?.[0]||null}
function header(c){const p=c.props||{},root=document.createElement('header');root.style.cssText=`display:flex;align-items:center;justify-content:space-between;min-height:64px;padding:0 18px;background:${p.menuBackground||'#fff'};color:${p.titleColor||'#111827'};border-bottom:1px solid #e5e7eb`;const title=document.createElement('strong');title.textContent=p.title||project?.name||'My App';const menu=document.createElement('div');menu.style.cssText='display:flex;gap:6px;flex-wrap:wrap';(p.items||Object.keys(definition.pages)).forEach(id=>{const page=definition.pages[id];if(page)menu.append(btn(page.name,()=>{currentPage=id;render()}))});root.append(title,menu);return root}
function component(c){const p=c.props||{},w=document.createElement('section');w.style.cssText='padding:12px';let e;if(c.type==='Header')w.append(header(c));else if(c.type==='Navigation'){e=document.createElement('nav');e.style.cssText='display:flex;gap:14px;flex-wrap:wrap';(p.items||[]).forEach(x=>e.append(btn(x,()=>{const id=pageId(x);if(id){currentPage=id;render()}})));w.append(e)}else if(c.type==='Hero Section'){e=document.createElement('div');e.style.cssText='padding:42px 24px;border-radius:16px;background:#111827;color:#fff';const h=document.createElement('h1');h.textContent=p.title||'Build something amazing';const t=document.createElement('p');t.textContent=p.text||'';e.append(h,t);if(p.button)e.append(btn(p.button,()=>{}));w.append(e)}else if(c.type==='Buttons'){w.append(btn(p.label||'Get Started',()=>{const id=pageId(p.link);if(id){currentPage=id;render()}}))}else if(c.type==='Cards'){e=document.createElement('article');e.style.cssText='padding:18px;border:1px solid #e5e7eb;border-radius:14px';const h=document.createElement('h3');h.textContent=p.title||'Card title';const t=document.createElement('p');t.textContent=p.text||'';e.append(h,t);w.append(e)}else if(c.type==='Images'||c.type==='Image'){if(p.url){e=document.createElement('img');e.src=p.url;e.alt=p.alt||'Image';e.style.cssText='display:block;max-width:100%;height:auto;border-radius:12px';w.append(e)}}else if(c.type==='Videos'){e=document.createElement('video');e.controls=p.controls!==false;e.src=p.url||'';e.style.width='100%';w.append(e)}else if(c.type==='Music Player'){const h=document.createElement('strong');h.textContent=p.title||'Now Playing';e=document.createElement('audio');e.controls=true;e.src=p.src||'';w.append(h,e)}else if(c.type==='Forms'){e=document.createElement('form');e.addEventListener('submit',x=>x.preventDefault());const h=document.createElement('h3');h.textContent=p.title||'Contact us';e.append(h);(p.fields||[]).forEach(x=>{const i=document.createElement('input');i.name=x;i.placeholder=x;i.style.cssText='display:block;width:100%;margin:7px 0;padding:10px;border:1px solid #d1d5db;border-radius:8px';e.append(i)});e.append(btn('Submit',()=>{}));w.append(e)}else if(c.type==='Text'){e=document.createElement('p');e.textContent=p.text||'';w.append(e)}else if(c.type==='Heading'){e=document.createElement('h1');e.textContent=p.text||'';w.append(e)}else if(c.type==='List'){e=document.createElement('ul');(p.items||[]).forEach(x=>{const li=document.createElement('li');li.textContent=x;e.append(li)});w.append(e)}else if(c.type==='Divider')w.append(document.createElement('hr'));else if(c.type==='Spacer'){e=document.createElement('div');e.style.height=`${Number(p.height)||24}px`;w.append(e)}else{e=document.createElement('div');e.textContent=p.text||c.type;w.append(e)}return w}
function render(){const page=definition.pages[currentPage];if(!page){canvas.textContent='Page not found';return}canvas.innerHTML='';canvas.style.background=page.styles?.background||'#fff';canvas.style.padding=page.styles?.padding||'24px';normalizeComponents(page.components||[]).forEach(c=>canvas.append(component(c)));document.title=`${project.name||'Live App'} — Indo`;status.textContent=`${project.name||'Live App'}${page.name?' • '+page.name:''}`}
async function load(){if(!slug)throw Error('Missing published app slug');const response=await fetch(`${GATE_URL}?slug=${encodeURIComponent(slug)}`,{cache:'no-store'});let body=null;try{body=await response.json()}catch{body={error:'Invalid server response'}}if(!response.ok){if(response.status===402)throw Error('This app trial has expired. Activation is required.');throw Error(body?.error||'Published app not found');}if(!body?.project)throw Error('Published app not found');project=body.project;definition=normalizeDefinition(project);currentPage=pageId('home')||Object.keys(definition.pages)[0];render()}
load().catch(error=>{status.className='error';status.textContent=error.message||'Could not load this app';});
