import { runApiAction } from './api-action.js';
import { bindApiResponse } from './response-binding.js';
import DataBinding from './data-binding.js';
function navigate(pageId){if(!pageId)return;const url=new URL(location.href);url.searchParams.set('page',pageId);history.pushState({},'',url);window.dispatchEvent(new PopStateEvent('popstate'));}
function formData(form){return Object.fromEntries(new FormData(form).entries())}
function resolve(value,context){if(typeof value!=='string')return value;return value.replace(/\{\{\s*form\.([^}]+)\s*\}\}/g,(_,key)=>context.formData?.[key.trim()]??'')}
function resolveObject(obj,context){return Object.fromEntries(Object.entries(obj||{}).map(([k,v])=>[k,resolve(v,context)]))}
function resolvePath(path,context){if(!path)return undefined;return String(path).split('.').reduce((value,key)=>value==null?undefined:value[key],context)}
function conditionValue(condition,context){const source=condition?.source;const field=condition?.field||'';if(source==='form')return field?resolvePath(`formData.${field}`,context):undefined;if(source==='event')return field?resolvePath(field,context):undefined;if(source==='static')return condition?.value??'';return condition?.value??''}
function conditionCompareValue(condition,context){if(condition?.compareSource==='form'){return condition.field?resolvePath(`formData.${condition.field}`,context):''}if(condition?.compareSource==='event'){return condition.compareField?resolvePath(condition.compareField,context):''}return condition?.compareValue??condition?.value??''}
function conditionMatches(condition,context){if(!condition)return true;const left=conditionValue(condition,context);const right=conditionCompareValue(condition,context);switch(condition.operator||'equals'){case'equals':return String(left??'')===String(right??'');case'not-equals':return String(left??'')!==String(right??'');case'contains':return String(left??'').includes(String(right??''));case'not-contains':return !String(left??'').includes(String(right??''));case'greater-than':return Number(left)>Number(right);case'less-than':return Number(left)<Number(right);case'truthy':return Boolean(left);case'falsy':return !left;default:return false}}
function workflowMatches(workflow,context){const conditions=Array.isArray(workflow.conditions)?workflow.conditions:(workflow.condition?[workflow.condition]:[]);return !conditions.length||conditions.every(condition=>conditionMatches(condition,context))}
async function executeAction(action,context={}){if(!action)return;
  if(action.type==='navigate')navigate(action.pageId||'home');
  else if(action.type==='show-message'){const node=document.createElement('div');node.textContent=resolve(action.message||'Done',context);node.style.cssText='position:fixed;right:20px;bottom:20px;z-index:9999;padding:12px 16px;border-radius:10px;background:#111827;color:#fff';document.body.appendChild(node);setTimeout(()=>node.remove(),2500)}
  else if(action.type==='set-value'&&action.selector){const el=document.querySelector(action.selector);if(el)el.value=resolve(action.value,context)}
  else if(action.type==='show-hide'&&action.selector){const el=document.querySelector(action.selector);if(el)el.style.display=action.visible===false?'none':''}
  else if(action.type==='api-call'){const config={...(action.config||action),url:resolve((action.config||action).url,context),body:resolve((action.config||action).body,context)};const result=await runApiAction(config,context);bindApiResponse(document,result);window.dispatchEvent(new CustomEvent('indo:api-result',{detail:result}));return result}
  else if(action.type==='database-create'){if(!action.tableId)throw new Error('Database table is required');const row=await DataBinding.create(action.tableId,resolveObject(action.data,context));window.dispatchEvent(new CustomEvent('indo:database-created',{detail:row}));return row}
  else if(action.type==='database-update'){if(!action.recordId)throw new Error('Record ID is required');const row=await DataBinding.update(action.recordId,resolveObject(action.data,context));window.dispatchEvent(new CustomEvent('indo:database-updated',{detail:row}));return row}
  else if(action.type==='database-delete'){if(!action.recordId)throw new Error('Record ID is required');await DataBinding.remove(resolve(action.recordId,context));window.dispatchEvent(new CustomEvent('indo:database-deleted',{detail:{recordId:action.recordId}}));return true}
}
async function runWorkflow(workflow,context){const results=[];for(const action of workflow.actions||[]){try{const result=await executeAction(action,context);results.push({actionId:action.id||null,ok:true,result});}catch(error){console.error('Indo workflow action failed',workflow.id,action.id,error);results.push({actionId:action.id||null,ok:false,error:error?.message||'Action failed'});window.dispatchEvent(new CustomEvent('indo:workflow-error',{detail:{workflowId:workflow.id,actionId:action.id||null,error}}));if(action.continueOnError===true||workflow.continueOnError===true)continue;break;}}return results}
export async function runWorkflows(projectId,eventType,context={}){const definition=window.IndoAppDefinition||{},workflows=Array.isArray(definition.workflows)?definition.workflows:[],results=[];for(const workflow of workflows.filter(w=>w.enabled&&w.trigger?.type===eventType&&workflowMatches(w,context))){results.push({workflowId:workflow.id||null,actions:await runWorkflow(workflow,context)});}return results}
export function mountWorkflowRuntime(projectId){if(!projectId)return()=>{};const click=e=>{if(e.target.closest('button,[data-indo-action]'))runWorkflows(projectId,'click',{event:e,target:e.target}).catch(console.error)},submit=e=>{e.preventDefault();runWorkflows(projectId,'submit',{event:e,form:e.target,formData:formData(e.target)}).catch(console.error)};document.addEventListener('click',click);document.addEventListener('submit',submit);runWorkflows(projectId,'page-load',{pageId:new URLSearchParams(location.search).get('page')||'home'}).catch(console.error);return()=>{document.removeEventListener('click',click);document.removeEventListener('submit',submit)}}
window.IndoWorkflowRuntime={runWorkflows,mountWorkflowRuntime,conditionMatches,workflowMatches};
